readthedocs.yaml

Signed-off-by: RaulSanchez <raul@eprosima.com>

Updated required Python version to Python3.7.

---

docs/requirements.txt

Signed-off-by: Eduardo Ponz Segrelles <eduardoponz@eprosima.com>

Update requirements [12271]

---

docs/first_steps/first_steps.rst
docs/spelling_wordlist.txt

Signed-off-by: jparisu <javierparis@eprosima.com>

Fix spelling

---

docs/notes/notes.rst

Signed-off-by: Eduardo Ponz Segrelles <eduardoponz@eprosima.com>

Correct notes list

---

docs/notes/notes.rst
docs/notes/previous_versions/v2.1.0.rst
docs/notes/previous_versions/v2.1.1.rst
docs/notes/previous_versions/v2.1.2.rst
docs/notes/previous_versions/v2.1.3.rst

Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>

[16904] Add ShapesDemo v2.1.0, v2.1.1, v2.1.2 and v2.1.3 release notes

---

docs/examples/ros2_compatibility.rst
docs/installation/linux_sources.rst

https://github.com/eProsima/ShapesDemo/pull/61

[17520] Enabled ROS2 typesupport by default when available

---

readthedocs.yaml

[20030] Fix Read the docs build 

---

docs/notes/notes.rst
docs/notes/previous_versions/v2.10.3.rst
docs/notes/previous_versions/v2.6.6.rst
docs/notes/previous_versions/v2.6.7.rst

[20030] Include v2.6.7 & v2.10.3 release notes in master

---

.github/workflows/mirror.yml

This PR adds a mirror workflow

Add a mirror workflow

---

docs/notes/notes.rst
docs/notes/previous_versions/v2.11.3.rst

This PR includes ShapesDemo v2.11.3 release notes in master latest documentation

[20032] Include ShapesDemo v2.11.3 release notes in master

---

docs/notes/notes.rst
docs/notes/previous_versions/v2.13.3.rst

This PR adds the release notes for Shapes Demo v2.14.0
- _N/A_: Applicable backports have been included in the description.

[20646] Add release notes for v2.14.0

---

docs/notes/notes.rst
docs/notes/previous_versions/v2.12.2.rst

Update release notes for 2.12.2
- N/A Applicable backports have been included in the description.

[20033] Update release notes for 2.12.2

---

docs/notes/notes.rst
docs/notes/previous_versions/v2.13.4.rst

This PR includes ShapesDemo v2.13.4 release notes in latest documentation (master)
- **N/A** Applicable backports have been included in the description.

[20723] Include v2.13.4 release notes

---

docs/notes/notes.rst
docs/notes/previous_versions/v2.6.8.rst

@Mergifyio backport 2.13.x 2.10.x
- _N/A_ Documentation tests pass locally.

[20826] Include v2.6.8 release notes in master

---

docs/notes/notes.rst
docs/notes/previous_versions/v2.13.5.rst

This PR includes the release notes of the recently release ShapesDemo v2.13.5 in master
@Mergifyio backport 2.14.x

[21100] Include v2.13.5 release notes in master

---

docs/notes/notes.rst
docs/notes/previous_versions/v3.1.0.rst

This brings the release notes from v3.1.1 into master
- _N/A_: Applicable backports have been included in the description.

[21832] Add release notes from `v3.1.1`

---

docs/notes/notes.rst
docs/notes/previous_versions/v3.0.2.rst

This brings the release notes from v3.0.2 into master
@Mergifyio backport 3.1.x
- __N/A__ Documentation tests pass locally.
- __N/A__ Applicable backports have been included in the description.

[21627] Add release notes from `v3.0.2`

---

docs/notes/notes.rst
docs/notes/previous_versions/v3.1.1.rst

This brings the release notes from v3.1.2 into master
- __N/A__: Documentation tests pass locally.
- __N/A__ Applicable backports have been included in the description.

[21627] Add release notes from `v3.1.2`

---

docs/notes/notes.rst

- **N/A** Documentation tests pass locally.
- **N/A** Applicable backports have been included in the description.

[22959] Typo 3.2.1 release title

---

docs/notes/previous_versions/previous_versions.rst
docs/notes/previous_versions/supported_versions.rst
docs/notes/previous_versions/v2.10.7.rst
docs/notes/previous_versions/v3.1.3.rst

- **N/A** Documentation tests pass locally.
- **N/A** Applicable backports have been included in the description.

[22800] Update versions after 2.10.x and 3.1.x EOLs

---

docs/notes/notes.rst
docs/notes/previous_versions/supported_versions.rst
docs/notes/previous_versions/v3.3.0.rst

This PR adds the release notes of v3.4.0

Release Notes v3.4.0
